### ISSUE TITLE
SeoComponent duplicates meta title and description

### ISSUE THREAD

**Issue by alessandro231** [Palmabit-IT/Sacajawea#1]
The `SeoComponent` inside `Head` component of Next.js doesn't override the meta title and description defined in `_document.js`, but it duplicates them.

I use it in this way:

```js
<Head>
   <SeoComponent title="My Title" description="My Desctiption" />
</Head>
```

**Comment by neomusic** [comment]
The SeoComponent returns a series of useful tags for the SEO.
This means that if you put the same tags within the same Head these are not overwritten.
To do this you need to insert the `SeoComponent` as the only child of the `Head` component and immediately reopen the `Head` component with the tags you want to overwrite

Example

```
 <Head>
      <title>foo</title>
      <SeoComponent title=“foo” description=“bar” />
  </Head>
 <Head>
      <meta property="og:description" content="baz">
  </Head>
```

in this way it is rendered
```
<meta property="og:description" content="baz">
```
not 
```
<meta property="og:description" content="bar">
```
